### ISSUE TITLE
Loading the backup files.

### ISSUE THREAD

**Issue by Krrishdhaneja** [stephengrice/linux-workspace#3]
How do I restore the backup files anywhere ?

**Comment by stephengrice** [comment]
The idea of this repository was that anything you commit to Git can be cloned somewhere else, which "restores" it. It's not the best solution, which is why I'm surprised so many people starred/forked this repo!
Basically, you can follow the README to (1) sync files to your home directory (though now I'd recommend just symlinking them instead of copying) and (2) clone all repos that you have defined in repos.csv.

So anything committed directly to linux-workspace will be loaded when you clone it. Anything you store in other repos defined in repos.csv will be restored when you use the clone-all script.

Let me know if you have more questions! 🙂
